hi


In [3]:
import numpy as np

arr = np.array([[1,2,3,4], [3,4,5,6], [7,8,9,10]]) 
print("Original Array")
print(arr)
print("Adding 2")
print(arr+2)
print("Multiplying by 10")
print(arr*10)
print("Division and subtraction also work!")
print((arr-1)/2)

Original Array
[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9 10]]
Adding 2
[[ 3  4  5  6]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Multiplying by 10
[[ 10  20  30  40]
 [ 30  40  50  60]
 [ 70  80  90 100]]
Division and subtraction also work!
[[0.  0.5 1.  1.5]
 [1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5]]
