In [9]:
import numpy as np
# ✔️ Q1. Create an array of 10 zeros
a = np.zeros(10)
print (a)

# ✔️ Q2. Create a NumPy array of numbers from 1 to 20
a1 = np.arange(1,21)
print(a1)

#✔️ Q3. Create an array of 5 ones
a3 = np.ones(5)
print(a3)

#✔️ Q4. Create an array of 7 random integers between 1 and 50
a4 = np.random.randint(1, 51, size=7)
print(a4)

#✔️ Q5. Create an array of even numbers from 0 to 30
a5 = np.arange(0,31,2)
print (a5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1. 1. 1. 1. 1.]
[45 22 31 38 47 20 33]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


UsageError: %%python3 is a cell magic, but the cell body is empty.
